dist: trusty
sudo: required
language: java
jdk:
- oraclejdk8
git:
  depth: 3
cache:
  directories:
  - "$HOME/.m2"
services:
- postgresql
before_script:
- psql -c 'create database frameworkeventstore;' -U postgres
- psql -c 'create database frameworkviewstore;' -U postgres
- psql -c 'create database frameworkfilestore;' -U postgres
- psql -c 'create database frameworksystem;' -U postgres
- psql -c "CREATE USER framework WITH PASSWORD 'framework';" -U postgres
addons:
  postgresql: '9.5'
  sonarcloud:
    organization: cjscommonplatform
    token:
      secure: MPrE0HzubH6Of0OeMlYuB5vEZNVfJE8wZG/iWdVmNHBVWWodEP4sO8s1GggKQk5rrHiSlVXs+G7OIM4X6Kg2HnjUj05G28IpirtkDnCLvIcSqAZxecO21tIBYwHn/mCdihHQOPjA8RFjc8+TSsRDNipeR3QvOzf6g5XZtOV/Ew+p5VoirIbI9jOO/qdOzHuQjZhARmI7HXqEmpkXJiObfyT5uJvO047lSbKA48VLWSfv2zFl5+8uymT+0g8fHPm9JWTNn7VLyKQQ4en7Cr9NC03Ahk8rXybB0qOrHj3fewtUGBp3pCa8bU6XaMFzSNHixueUG2mxxxI9ROB7nz+19CSOGafXZsygjDqPeT8D1wHHGGBmc90WQE3JhU9YFMXKnx5/a8OJyIAGRUE81wt3FsJUu+OvIHdQEOlM7geWYv6P52VbgmJSSvMgRnzNE3seq0LSsFxQXAQmAmDLWwWz0t2wbzO8dUmmU4jn5xoqSe2RBENaD1vDG37rvi8aGrr+Xg2005/8yIvlr+7ZZbeiHdYXqzbiDdYQyGjr8FaJLI3WPBtCRhsvJBgdQhuMFI/V44ntwAP6CzOty9Gfldlp+ybaY9UcFSKbGxBcrHPJfsS2ajgPUjW1K8KBFc7IKfy/XWhBsWOEHgVb2n4AZSV/nFTpK4HwpvHid0bEHcyTpk8=
before_install:
- git clone https://github.com/CJSCommonPlatform/travis-settings.git target/travis-settings
- ln -sfT ${PWD}/target/travis-settings/settings.xml ${HOME}/.m2/settings.xml
- ln -sfT ${PWD}/target/travis-settings/mvnw mvnw
- ln -sft ${PWD} ${PWD}/target/travis-settings/.mvn
install: "${PWD}/target/travis-settings/java/install.sh -e -DexcludeGroupIds=uk.gov.justice.service,uk.gov.justice.services"
script: "${PWD}/target/travis-settings/java/script-install.sh coveralls:report sonar:sonar"
after_success: "${PWD}/target/travis-settings/java/after_success.sh"
notifications:
  slack:
    secure: fPlaMvrczZ2riJ4tjMOAqxSGj4JfxGlH/K08knLgG4T/n6EL4LN4+184Npz9XueNbV3m26WUrPkbXEiWXpqkKsbwcZXqqnFxGacGiyxv7LeBeQLYp7NFeARAyB5qDwUpjHlCPAEoAeyeGsZNrpui/wceY4j1tB7ObfdwbxLzAO0tekdbwitSaK1cc7V2sVHkBYr7ChuC+dVO1pshPw0EVTmzPioS8nfFKPaxWoMgyRAuYe7MD0U7DxNQ4Wzsb7tpfd5Oom1wLXyZ7M3wwSMMamIAAxHVG389Az6YvN7hXQggTGDawf/YwVOaoMR2bh7uHBCOiNZO1GbRTOA7IuTPwT7GsK94THRtfvqNm7RFBPkoD4657FATnk2o5c7QNTY3dAlYLsxLnS6mVTL/vAbqC7BbDHo/UGsxmOusQtKt8sRoL8pOCEInHaS3b88Osl7u7oYO/E4YTptdnkEe8tNyWWdx34nEUT0j1Mu/VAN38YcgTMUuiBU6chkMJ5BjIHisJlAAnBJ9VGgF9liqnigNwAGhbrHZPyAlKUX8HLejpD+t4aR0UaEvvauh6aHh4pYm0mZra4zOBC/lBDOXqsu5ajHL8LpHc6j+5FrmNwciiTVoxdud2S4c0U2ymr3L07ivX+UyhoraS9oSH3v7L73Q4NyvuAmD8Zc0xw/cR4Pff9c=
env:
  global:
  - PGPORT=5432
  - secure: grVrC6MdVIMFXNWl0ByQAcs9KckX/Fac68lJWaK07vUD/Q/Key4C4Df6FRUABL82pmnPZALcBISZ4bI7dILxnPdHLZ7m7Cf82V2c25mv8SkJ09uETbBQg8y4ohH8u5VGhvmEi2/5qFSfHY2CgswMdq8Ixw/823tdKVNSJ0rh60O/2yQS8MJsZ182oJRcJnpt10qM2VOkBb7z9QljnaJrseVrAg1g5sta2DYq3pC6LAqRvO0FR+f9b9o6Nwx5+rO4rj+nzUpwGkBSt/x1cxbboGgsISpPwnYzeuEvK460WIYJv4x3OVF731KYQiS66f5bRU+3iHGOAEwRKFz0uq2LM6mmFBKNaly2SHu+VCwGpWGGBi3BJZlei8dx/I/piaIF7COgDPFeHd/JSqQ0YEvO4EWYngHI/b1x62WlatgVijzsVA2x6XM/Rycl/EK81vP+G4ivsTVx4QK8nMgWxQPEMbU36XjtW1lOnuTH+IMwsz/hNop3DIJQf+laAaNAMD7Ubi1M+iESuZGnfKdEHMJNwiXq2Kjk7notK/+G5ZiY0G13DgyuQ8TzHWl89K80PFqPlBIKp5j7EmDkR6t4kyDDZVrDXlpb9a0xLNaeub2bjLjWNWACkIRpU+TgAfKuDFlNGgaeYCiyz3hEZiEa5GVfDA+BgWoanA1VD1HAZR0MrPg=
