#%RAML 0.8
title: Cakeshop Query
baseUri: http://localhost:8080/cakeshop-custom-api/custom/api/rest/cakeshop
version: v0.1
mediaType: application/json
protocols: [ HTTP, HTTPS ]

/ovens:
  description: curent status of the ovens
  get:
    description: |
        ...
        (mapping):
            responseType: application/vnd.cakeshop.status+json
            name: cakeshop.ovens-status
        ...
    responses:
      200:
        body:
          application/vnd.cakeshop.status+json:
            schema: !include json/schema/cakeshop.ovens-status.json
            example: !include json/ovens-status.json
